### ISSUE TITLE
Action Not Working Due to Asset Name Changes Since Version 1.0.35

### ISSUE THREAD

**Issue by fa0311** [mwilliamson/setup-wabt-action#3]
Dear Maintainers,

I apologize for the interruption, but I would like to kindly submit an issue.

This project has not been maintained for over two years, but I would be grateful if you could address this issue. The action does not work since the asset names have been slightly changed from version  [1.0.35](https://github.com/WebAssembly/wabt/releases/tag/1.0.35).

Additionally, as a suggestion, it might be helpful to add an option to allow overwriting the version.

Thank you very much for your consideration.

**Comment by mwilliamson** [comment]
Thanks for the report, this should be fixed in v3.

> Additionally, as a suggestion, it might be helpful to add an option to allow overwriting the version.

Sorry, I'm not sure what you mean. You can already choose what wabt version to use when using the action (and indeed, it's required).

**Comment by fa0311** [comment]
> Thanks for the report, this should be fixed in v3.

Thank you!

> Sorry, I'm not sure what you mean. You can already choose what wabt version to use when using the action (and indeed, it's required).

Don't worry about it. It's a bad suggestion.
